In [1]:
import random

In [2]:
a=random.random()
print(a)

0.7709004668589684


In [4]:
b=random.uniform(1,10)
b

2.15573783852167

In [8]:
c=random.randint(1,10)
c

3

In [11]:
d=random.randrange(1,10)
d

9

In [15]:
e=random.normalvariate(0,1) ## mean of zero and Std dev of 1 
print(e) ## Normalized graph

2.9422406251191684


In [16]:
## Sequences 
mylist=list('ABCDEFGH')
print(mylist)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']


In [17]:
f=random.choice(mylist)

In [19]:
f

'H'

In [21]:
g=random.sample(mylist,3)
g

['A', 'C', 'D']

In [23]:
h=random.choices(mylist,k=3)
h

['F', 'F', 'E']

In [28]:
random.shuffle(mylist)
print(mylist)

['G', 'B', 'F', 'A', 'D', 'C', 'H', 'E']


In [29]:
random.seed(1)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2


In [30]:
random.seed(1)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2


In [31]:
random.seed(2)
print(random.random())
print(random.randint(1,10))

0.9560342718892494
1


In [32]:
random.seed(1)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2


In [33]:
random.seed(2)
print(random.random())
print(random.randint(1,10))

0.9560342718892494
1


In [34]:
import secrets

In [36]:
## used for passwords , account etc
## disadvantages as it takes more time and generate true random no 
a=secrets.randbelow(10)
a

9

In [40]:
b=secrets.randbits(4) ## returns bits and bites 
b

5

In [42]:
mylist=list("ABCDEFGH")
a=secrets.choice(mylist)
a

'D'

In [43]:
import numpy as np 

In [44]:
## array with random floats 
a=np.random.rand(3)
a

array([0.43532193, 0.38624839, 0.70208932])

In [45]:
a=np.random.rand(3,3)
a

array([[0.67264126, 0.24706941, 0.65110449],
       [0.91250507, 0.25655581, 0.61980307],
       [0.4537467 , 0.16084254, 0.64972171]])

In [53]:
b=np.random.randint(0,10, (3,4))
print(b)

[[0 8 1 5]
 [6 1 9 3]
 [0 2 3 9]]


In [57]:
## shuffle method 
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
np.random.shuffle(arr)
arr

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [61]:
np.random.seed(1)
print(np.random.rand(3,3)) ## gives same array use numpy method for seed generators 

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]


# Decoraters 

In [ ]:
@mydecorater ## its is a func that takes another func as argument and extends the behaviour the func of the funct without modfifying it
def dosomething():
    pass

In [88]:
def start_end_decorater(func):
    def wrapper(*args,**kwargs):
        print('Start')
        func(*args,*kwargs)
        print('End')
        return result
    return wrapper
@start_end_decorater
def add5(x):
    return x+5

result=add5(10)
print(result)
    
#def printname():
  #  print('alex')
##printname=start_end_decorater(printname)
##printname()

Start
End
None


In [91]:
import functools

In [93]:
def start_end_decorater(func):
    @functools.wraps(func)
    def wrapper(*args,**kwargs):
        print('Start')
        func(*args,*kwargs)
        print('End')
        return result
    return wrapper
@start_end_decorater
def add5(x):
    return x+5

print(help(add5))
print(add5.__name__)

Help on function add5 in module __main__:

add5(x)

None
add5


In [94]:
def start_end_decorater(func):
    @functools.wraps(func)
    def wrapper(*args,**kwargs):
        print('Start')
        func(*args,*kwargs)
        print('End')
        return result
    return wrapper
@start_end_decorater
def add5(x):
    return x+5

print(add5.__name__)

add5


In [96]:
def my_decorator(func):
    @functools.wraps(func)
    def wrapper(*args,**kwargs):
        ## do something
        
        result=func(*args,*kwargs)
        ## dosomething
     
        return result
    return wrapper
@start_end_decorater
def add5(x):
    return x+5

print(help(add5))
print(add5.__name__)

Help on function add5 in module __main__:

add5(x)

None
add5


In [103]:
## decorators can also take arguments 

def repeat(num_times):
    def decorator_repeat(func):
        @function.wraps(func)
        def wrapper(*args,**kwargs):
            for _ in range(num_times):
                
                result=func(*args,**kwargs)
            return result
        return wrapper
    return decorator_repeat

@repeat(num_times=3)
def greet(name):
    print('hello',name)
    


NameError: name 'function' is not defined

In [105]:
class CountCalls:
    def __init__(self,func):
        self.func=func
        self.num_calls=0
        
    def __call__(self,*args,**kwargs):
        print('hi there')
        
cc=CountCalls(None)
cc()
        

@CountCalls
def say_hello():
    print('hello')

hi there


In [107]:
class CountCalls:
    def __init__(self,func):
        self.func=func
        self.num_calls=0
        
    def __call__(self,*args,**kwargs):
        self.num_calls += 1
        print(f'this is executed {self.num} times')
        return self.func(*args,**kwargs)
        
        

@CountCalls
def say_hello():
    print('hello')

In [108]:
say_hello()

AttributeError: 'CountCalls' object has no attribute 'num'

In [ ]:
say_hello

# Generators 